
import { GoogleGenAI } from "@google/genai";
import { GenerationSettings } from "../types";

export const generateMockup = async (
  designBase64: string,
  stylePrompt: string,
  settings: GenerationSettings
): Promise<string> => {
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
  
  const mimeType = 'image/png'; 
  
  // Resolve prompt placeholders
  let finalPrompt = stylePrompt;
  
  // Replace gender/subject
  const genderSubject = settings.gender === 'Male' 
    ? 'African man' 
    : settings.gender === 'Female' 
      ? 'African woman' 
      : 'African person';
  finalPrompt = finalPrompt.replace(/\[SUBJECT\]/g, genderSubject);
  
  // Replace color
  finalPrompt = finalPrompt.replace(/\[COLOR\]/g, settings.color.toLowerCase());
  
  try {
    const response = await ai.models.generateContent({
      model: settings.model,
      contents: {
        parts: [
          {
            inlineData: {
              data: designBase64.split(',')[1],
              mimeType: mimeType,
            },
          },
          {
            text: finalPrompt,
          },
        ],
      },
      config: {
        imageConfig: {
          aspectRatio: settings.aspectRatio,
          ...(settings.model === 'gemini-3-pro-image-preview' ? { imageSize: settings.quality } : {})
        }
      }
    });

    let imageUrl = '';
    
    if (response.candidates && response.candidates[0].content.parts) {
      for (const part of response.candidates[0].content.parts) {
        if (part.inlineData) {
          imageUrl = `data:image/png;base64,${part.inlineData.data}`;
          break;
        }
      }
    }

    if (!imageUrl) {
      throw new Error("No image was generated by the model.");
    }

    return imageUrl;
  } catch (error: any) {
    console.error("Gemini API Error:", error);
    if (error.message?.includes("Requested entity was not found")) {
      throw new Error("API_KEY_RESET");
    }
    throw error;
  }
};

export const checkApiKeySelection = async (): Promise<boolean> => {
  if (typeof (window as any).aistudio?.hasSelectedApiKey === 'function') {
    return await (window as any).aistudio.hasSelectedApiKey();
  }
  return true; 
};

export const openApiKeySelector = async () => {
  if (typeof (window as any).aistudio?.openSelectKey === 'function') {
    await (window as any).aistudio.openSelectKey();
  }
};
